services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.production
        command: make test
        volumes:
            - ".:/app"
        image: "iggorbunov/docker-project-74"